# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml
linter:
  rules:
    lines_longer_than_80_chars: false
    non_constant_identifier_names: false
    flutter_style_todos: false
    unnecessary_brace_in_string_interps: false
    avoid_function_literals_in_foreach_calls: false
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"